export default [
  {
    title: "Starter",
    desc: "Designed for getting started with basic support.",
    price: "Free",
    priceFrequency: "",
    varient: "light",
    features: [
      "10 Smart Tag Tracking",
      "Single Location",
      "Warranty Status",
      "Maintenance Details",
      "File Attachments",
      "Custom Forms",
      "Maintenance Updates",
      "Analytics",
    ],
  },
  {
    title: "Business",
    desc: "Designed for mid-size businesses with dedicated support.",
    price: "$99",
    priceFrequency: "/month",
    varient: "dark",
    features: [
      "100 Smart Tag Tracking",
      "Single Location",
      "Warranty Status",
      "Maintenance Details",
      "File Attachments",
      "Custom Forms",
      "Maintenance Updates",
      "Compliance Reports",
      "Inventory Management",
      "Analytics",
    ],
  },
  {
    title: "Enterprise",
    desc: "Large enterprises with dedicated support and catering for dynamic needs.",
    price: "Talk to us",
    priceFrequency: "",
    varient: "light",
    features: [
      "Unlimited Smart Tag Tracking",
      "Multi-Location",
      "Warranty Status",
      "Maintenance Details",
      "File Attachments",
      "Custom Forms",
      "Maintenance Updates",
      "Compliance Reports",
      "Inventory Management",
      "Analytics",
    ],
  },
] as Price[];
